"$schema" = "./node_modules/wrangler/config-schema.json"
name = "zemonie-web-worker"
compatibility_date = "2026-04-03"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[vars]
VITE_SERVER_URL = "https://api.zemonie.site"

[[routes]]
pattern = "www.zemonie.site"
custom_domain = true
